# .air.toml

[build]
  cmd = "go run ./src/server.go"
  bin = "bin/main"
  full_bin = "false"
  include_ext = ["go", "tpl", "tmpl", "html", "js", "css"]
  exclude_dir = ["assets", "node_modules"]
  exclude_file = []
  include_dir = []
  log = "debug"
  tmp_dir = "tmp"
  full_bin = "false"

[log]
  color = "true"
  time = "true"

[watch]
  delay = 1000
  # Write your custom file/dir to watch, including the "go" and "non-go" files
  full_bin = "false"
  include = ["."]
  exclude = ["assets", "node_modules"]
