version: '3.8'

services:
  mc-iam-manager:
    container_name: mciam-manager
    build:
      context: ./dockerfiles/mc-iam-manager
      dockerfile: Dockerfile.mciammanager
    ports:
      - "${PORT:-8082}:${PORT:-8082}" # Use PORT from .env, default to 8082 if not set
    env_file:
      - .env # Load environment variables from .env file
    # depends_on: # Removed dependencies for standalone mode
    #   postgres:
    #     condition: service_healthy
    #   keycloak:
    #     condition: service_healthy
    networks:
      - mciam-network # Keep network for potential external connections if needed
    restart: unless-stopped
    # Add healthcheck if needed for mc-iam-manager

networks:
  mciam-network:
    driver: bridge
