@startuml

title "Update Workspace"

actor User as user

participant "app.go" as app
participant "workspaces.go" as controller
participant "workspacesHandler.go" as handler
participant "Database" as db

user    -> app : PUT: /api/ws/workspace/id/{workspaceId}
app    -> controller : UpdateWorkspace
controller -> handler : UpdateWorkspace
handler -> db :
db -> handler :
handler -> controller :
controller -> app :
user <- app : return successMessage | json message

@enduml
