@startuml

title "SearchRoleByName"

actor User as user

participant "app.go" as app
participant "roles.go" as controller
participant "rolesHandler.go" as handler
participant "Database" as db

user    -> app : GET: /api/role/role/id/{roleId}
app    -> controller : SearchRolesByName
controller -> handler : SearchRolesByName
handler -> db : return RoleList
db -> handler :
handler -> controller :
controller -> app :
user <- app : return successMessage | RoleList

@enduml
