@startuml

title "Create Project"

actor User as user

participant "app.go" as app
participant "projects.go" as controller
participant "projectsHandler.go" as handler
participant "Database" as db

user    -> app : POST: /api/prj
app    -> controller : CreateProject
controller -> handler : CreateProject
handler -> db :
db -> handler :
handler -> controller :
controller -> app :
user <- app : return successMessage | json message

@enduml
