@startuml

title "GetProjectById"

actor User as user

participant "app.go" as app
participant "projects.go" as controller
participant "projectsHandler.go" as handler
participant "Database" as db

user    -> app : GET: /api/prj/project/id/{projectId}
app    -> controller : GetProjectById
controller -> handler : GetProjectById
handler -> db :
db -> handler :
handler -> controller :
controller -> app :
user <- app : return successMessage | json message (ProjectOne)

@enduml
