networks:
  mc-iam-manager-network:

services:
  mc-iam-manager-kc:
    container_name: mc-iam-manager-kc
    build:
      context: ./
      dockerfile: ./dockerfiles/Dockerfile.keycloak
    networks:
      - mc-iam-manager-network
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
    env_file:
      - .env
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://mc-iam-manager-db:5432/${IAM_POSTGRES_DB}
      KC_DB_USERNAME: ${IAM_POSTGRES_USER}
      KC_DB_PASSWORD: ${IAM_POSTGRES_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      # KC_LOG_LEVEL: DEBUG
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
    volumes:
      - ./dockerfiles/import/realm-import.json:/opt/keycloak/data/import/realm-import.json
      - ./container-volume/mc-iam-manager/keycloak/data/:/opt/keycloak/data/
    depends_on:
      - mc-iam-manager-db
    command: 
      - start-dev 
      - --import-realm 
      - --verbose 
      - --features=token-exchange  
      - --https-key-store-file=/opt/keycloak/conf/server.keystore
      - --https-key-store-password=password123

  mc-iam-manager-db:
    container_name: mc-iam-manager-db
    image: postgres:14-alpine
    networks:
      - mc-iam-manager-network
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
    env_file:
      - .env
    volumes:
      - ./container-volume/mc-iam-manager/postgres/postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${IAM_POSTGRES_DB}
      POSTGRES_USER: ${IAM_POSTGRES_USER}
      POSTGRES_PASSWORD: ${IAM_POSTGRES_PASSWORD}
