version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx-cert.conf:/etc/nginx/nginx.conf
      - ~/.m-cmp/data/certbot/conf:/etc/letsencrypt
      - ~/.m-cmp/data/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - certbot

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ~/.m-cmp/data/certbot/conf:/etc/letsencrypt  
      - ~/.m-cmp/data/certbot/www:/var/www/certbot
    entrypoint: >
      /bin/sh -c 'certbot certonly --webroot --webroot-path=/var/www/certbot --email ${EMAIL} --agree-tos --no-eff-email -d ${DOMAIN} --debug;'
