title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://mzc-csc.github.io/mc-iam-manager

aux_links:
  Template Repository: https://github.com/MZC-CSC/mc-iam-manager
